version: 2
jobs:
  tests:

    docker:
      - image: ruby:latest
    steps:
      - checkout

      - run:
          name: Check Twitter handles
          command: bash twitter.rb
          working_directory: tests

      - run:
         name: Check Facebook handles
         command: bash facebook.rb
         working_directory: tests

      - restore_cache:
          keys:
            - awis-cache

      - run:
          name: Check Alexa ranking
          command: bash alexa.rb
          working_directory: tests

      - save_cache:
          key: awis-cache
          paths:
            - "/tmp/alexa/*"

workflows:
  version: 2
  workflow:
    jobs:
    - tests
